improvement in codebuild

diff --git a/buildspec_gnu.yml b/buildspec_gnu.yml
--- a/buildspec_gnu.yml
+++ b/buildspec_gnu.yml
@@ -11,6 +11,18 @@ phases:
       - echo Executing install phase
       - echo $CODEBUILD_WEBHOOK_TRIGGER
       - echo $CODEBUILD_WEBHOOK_BASE_REF
+      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
+      - echo $CODEBUILD_WEBHOOK_EVENT
+      - echo $CODEBUILD_BUILD_SUCCEEDING
+
+      - if ["$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_MERGED"];
+        then export CODEBUILD_GIT_BRANCH="develop";
+        echo "Merging to develop";
+        else CODEBUILD_GIT_BRANCH="$(git branch -a --contains $CODEBUILD_SOURCE_VERSION | sed -n 2p | awk '{ printf $1 }')";
+        export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/};
+        fi
+      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
+      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"
 
       - echo MPI setup for Docker
       - mkdir -p /var/run/sshd
@@ -42,13 +54,25 @@ phases:
     commands:
       - echo Executing pre_build phase
       - cd ../
-      - my_branch=$(echo $CODEBUILD_WEBHOOK_TRIGGER| cut -d"/" -f2-)
-      - echo $my_branch
+
       - git lfs install
       - cp ~/.gitconfig /home/jcsdauser/
+ 
+      # saber-bundle
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/saber-bundle saber-bundle
-      - git clone -b $my_branch https://$GIT_USER:$GIT_PASS@github.com/jcsda/saber saber-bundle/saber
+      - cd saber-bundle
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in saber-bundle repo"
+      - cd $CODEBUILD_SRC_DIR
+
+      # saber
+      - git clone -b $CODEBUILD_GIT_BRANCH https://$GIT_USER:$GIT_PASS@github.com/jcsda/saber saber-bundle/saber
+
+      # fckit
       - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fckit saber-bundle/fckit
+      - cd saber-bundle/fckit
+      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fckit repo"
+      
+      # atlas  
       - git clone -b 0.18.1 https://$GIT_USER:$GIT_PASS@github.com/ecmwf/atlas saber-bundle/atlas
 
       - mv saber-bundle /jcsda/
@@ -61,15 +85,19 @@ phases:
       - echo Executing build phase
       - su - jcsdauser -c "cd /build_container 
         && ls
-<<<<<<< HEAD
-=======
         && export FC=mpifort
         && export CC=mpicc
         && export CXX=mpicxx
->>>>>>> develop
         && ecbuild /jcsda/saber-bundle/
         && make -j4
         && ctest" 
   post_build:
     commands:
       - echo Executing post_build phase
+      - echo $CODEBUILD_BUILD_SUCCEEDING
+      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ];
+        then echo "Build Failing";
+        su - jcsdauser -c "cd /build_container/ufo
+        && ctest -VV --rerun-failed";
+        else echo "CODEBUILD_BUILD_SUCCEEDING=$CODEBUILD_BUILD_SUCCEEDING";
+        fi
